#pragma config(Motor,  port6,           shootingMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {
		if (vexRT[Btn8U] == 1) {
			motor[shootingMotor] = 127;
	  } else {
	  	motor[shootingMotor] = 0;
	  }
	  if (vexRT[Btn6U]) {
	  	motor[armMotor] = 127;
	  } else if (vexRT[Btn6D]) {
	  	motor[armMotor] = -128;
	  } else {
	  	motor[armMotor] = 0;
	  }
	}
}
