#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           beltMotor1,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backLeftMotor, tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           shootingMotor1L, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           shootingMotor1R, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shootingMotor2R, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           shootingMotor2L, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           frontRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backRightMotor, tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port10,          beltMotor2,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition);
#pragma autonomousDuration(20);
#pragma userControlDuration(120);

#include "Vex_Competition_Includes.c";

int getTicks(int distance) { // distance in inches
	float circumference = 4*3.1415;

	float ticksPerRotation = 261.333; //627.2 for high torque, 392 for high speed,
	//261.333 ticks for turbo gear set

	float numRotations = distance / circumference;

	float ticks = ticksPerRotation*numRotations;

	return ticks;
}

int shootingMotorSpeed = 0;
task setShooting() {
	motor[shootingMotor1L] = shootingMotorSpeed;
	motor[shootingMotor2L] = shootingMotorSpeed;
	motor[shootingMotor1R] = shootingMotorSpeed;
	motor[shootingMotor2R] = shootingMotorSpeed;
}

void pre_auton() {
	nMotorEncoder[backLeftMotor] = 0;
	nMotorEncoder[backRightMotor] = 0;
}
task autonomous {
	while (nMotorEncoder[backRightMotor] < getTicks(60)) {
		// do stuff
		motor[backLeftMotor] = 63;
		motor[backLeftMotor] = 63;
		motor[frontRightMotor] = 63;
		motor[frontRightMotor] = 63;
	}

	AutonomousCodePlaceholderForTesting();// remove after functioning code
}

task usercontrol() {
	{

		int beltSpeed = 0;
		while (true) {
			int x  = vexRT[Ch1];  // Right Joystick X value
			int y = vexRT[Ch3];   // Left Joystick Y value

			if (abs(x) < 10) {
				x = 0;
			}
			if (abs(y) < 10) {
				y = 0;
			}

			int speed = y;

			int differential = x;

			int right = speed + differential;
			int left = speed - differential;

			if (right > 127) {
				right = 127;
			}
			if (right < -128) {
				right = -128;
			}
			if (left > 127) {
				left = 127;
			}
			if (left < -128) {
				left = -128;
			}

			int frontLeft = left;
			int frontRight = right;
			int backLeft = left;
			int backRight = right;

			int mech = vexRT[Ch4];  // Left Joystick X value
			if (abs(mech) < 10) {
				mech = 0;
			}

			frontLeft += mech;
			frontRight += mech;

			backLeft -= mech;
			backRight -= mech;

			if (frontLeft < -128) {
				frontLeft = -128;
			}
			if (frontRight < -128) {
				frontRight = -128;
			}
			if (backLeft < -128) {
				backLeft = -128;
			}
			if (backRight < -128) {
				backRight = -128;
			}
			if (frontLeft > 127) {
				frontLeft = 127;
			}
			if (frontRight > 127) {
				frontRight = 127;
			}
			if (backLeft > 127) {
				backLeft = 127;
			}
			if (backRight > 127) {
				backRight = 127;
			}
			motor[frontLeftMotor] = frontLeft;
			motor[backLeftMotor] = backLeft;
			motor[frontRightMotor] = frontRight;
			motor[backRightMotor] = backRight;

			if (vexRT[Btn5U] == 1) {
				beltSpeed = 64;
				} else if (vexRT[Btn5D] == 1) {
				beltSpeed = 0;
			}
			motor[beltMotor1] = beltSpeed;
			motor[beltMotor2] = beltSpeed;

			if (vexRT[Btn8U] == 1) {
				shootingMotorSpeed = 100;
				startTask(setShooting);
				} else {
				shootingMotorSpeed = 0;
				startTask(setShooting);
			}
		}

		UserControlCodePlaceholderForTesting();
	}
}
