#pragma config(Sensor, in1,             lineFollow,     sensorLineFollower)
#pragma config(Sensor, in2,             potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port2,           backLeftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           beltMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shootingMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           frontRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Sensor, dgtl8,           sonarSensor, sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool turn180 = false;
bool armDown = false;
bool armUp   = false;

int fL = 0,fR = 0,bL = 0,bR = 0;

// for movement
int speed;
int sonar_value;
int distance = 25;

task lineTracking {
	while (true) {

		sonar_value = SensorValue(sonarSensor);

		if (sonar_value < 0) {
			speed = 127;
			} else {
			speed = (sonar_value - distance)^2;
		}
		if (speed < 5)
			turn180 = true;

		int threshold = 505; // lowest + highest / 2
		fL = speed;
		bL = speed;
		fR = speed;
		bR = speed;

		if (SensorValue(lineFollow) < threshold) {
			// counter-steer left
			fL += 64;
			bL += 64;
			fR -= 64;
			bR -= 64;
			} else {
			// counter-steer right
			fL -= 64;
			bL -= 64;
			fR += 64;
			bR += 64;
		}

		break;
	}
	stopTask(lineTracking);
}


task controlArm {
	while (armDown) {
		// do stuff
		// put arm down
		motor[armMotor] = -10;
		if (SensorValue(potentiometer) > 3500) { // range is 0-4096 for over 200 degrees
			motor[armMotor] = 0;
			break;
		}
	}
	armDown = false;
	while (armUp) { // WE NEED TO KNOW WHEN TO BRING UP THE ARMS!!!!
		// do stuff
		// put arm up
		motor[armMotor] = 10;
		if (SensorValue(potentiometer) < 1000) { // range is 0-4096 for over 200 degrees
			motor[armMotor] = 0;
			break;
		}
	}
	armUp = false;
}
task movement {
	while (true) {


		if (speed >= 0 && speed < 4) { // may have to tweak
			 armDown = true;
		}

		// do stuff
		wait1Msec(1000); // wait a second before figuring out what to do.
		if (!armDown && !turn180) {
			startTask(lineTracking);
		}

		// move

		// turn 180degrees
		if (turn180) {
			///
			///
			///
			///
			armDown = true;
			turn180 = false;
		}
		break;
	}
}
task shootingControl {
	while (true) {
		// do stuff
		break;
		// be able to shoot balls
	}

}

task main() { // this method is methodical
	startTask(controlArm);
	startTask(movement);
	startTask(shootingControl);
	while (true) {
		if (fL < -128)
			fL = -128;
		if (fR < -128)
			fR = -128;
		if (bL < -128)
			bL = -128;
		if (bR < -128)
			bR = -128;
		if (fL > 127)
			fL = 127;
		if (fR > 127)
			fR = 127;
		if (bL > 127)
			bL = 127;
		if (bR > 127)
			bR = 127;

		motor[frontLeftMotor] = fL;
		motor[frontRightMotor] = fR;
		motor[backLeftMotor] = bL;
		motor[backRightMotor] = bR;

		if (false) 		// if button
			stopAllTasks();

		break;
	}
}
